### PR TITLE
Ui redesign

### LINKED ISSUE #146: Frontend Redesign
I envision a tabbed list on the left side of the page for categories and feeds. The item cards will fill up the rest of the page.

This redesign will also lower the number of API calls we need to make to the server, which will make for a more seamless user experience.

### PR DESCRIPTION
**Pull request by alexgerstein**
Added a side nav bar to look at feeds and categories. Resolves #146.

### CODE REVIEW

**Comment by alexgerstein** [comment]
At present, only unread feed counts are updated. Once #160 is merged into master, I'll move categories to their own table and fix unread category counts as well.

**Comment by swglad** [comment]
The latest push looks awesome! Love the icons and login form. Also very impressed that reading items in a feed changes the unread count instantaneously. That's really really cool. 

Just wanted to list some bugs here that I noticed. Some can clearly be for future PR/issues, but figured I'd take the time to list them anyway while I'm playing with the new UI:

1. ENHANCE: scraper.py: Move item image_url extraction (lines 30-35) into _store_items, so that quitting the seed function early still gets item image's. 
2. BUG: Subscribe-on-Upvote doesn't work (no modal appears). *(Very important for this PR)*
    * Go to Feeds > Engadget
    * Unsubscribe from feed
    * Upvote an item --> issue: no modal appears
3. BUG: Collapsible sidebar does not work collapse/reveal correctly in mobile/small mode, and resizing the browser causes weird behavior *(Kinda important for this PR)*
    * Shrink browser size
    * Click "hamburger" menu reveal
    * Click "hamburger" menu collapse 
4. BUG: unsubscribing from a feed doesn't delete it from your side-bar Feeds list 
5. ENHANCE: Can you leave the format of "Browse" consistent both before/after login? Seems weird that it changes.
6. BUG: Scrolling in card-reveal is acting weird. Specifically, sometimes (not every time) the card info won't scroll unless you're touching the very bottom edge of the card. Other times, anywhere inside the card-reveal lets you scroll.

**Comment by alexgerstein** [comment]
Did you do a hard reset in your browser? Some of these issues I’m not experiencing so it might be a caching issue. Can you please try the reset and edit what changes in your comment? Also, please make issues for the items listed that don’t have to do with this PR. It will help prevent feature creep and help remember these issues when they disappear after the PR is merged. 

-- 
Alex Gerstein
gerstein.alex@gmail.com

On March 26, 2015 at 6:41:04 PM, Scott Gladstone (notifications@github.com) wrote:

The latest push looks awesome! Love the icons and login form. Also very impressed that reading items in a feed changes the unread count instantaneously. That's really really cool.

Just wanted to list some bugs here that I noticed. Some can clearly be for future PR/issues, but figured I'd take the time to list them anyway while I'm playing with the new UI:

ENHANCE: scraper.py: Move item image_url extraction (lines 30-35) into _store_items, so that quitting the seed function early still gets item image's.
BUG: Subscribe-on-Upvote doesn't work (no modal appears). (Very important for this PR)
Go to Feeds > Engadget
Unsubscribe from feed
Upvote an item --> issue: no modal appears
BUG: Collapsible sidebar does not work collapse/reveal correctly in mobile/small mode, and resizing the browser causes weird behavior (Kinda important for this PR)
Shrink browser size
Click "hamburger" menu reveal
Click "hamburger" menu collapse
BUG: unsubscribing from a feed doesn't delete it from your side-bar Feeds list
ENHANCE: Can you leave the format of "Browse" consistent both before/after login? Seems weird that it changes.
BUG: Scrolling in card-reveal is acting weird. Specifically, sometimes (not every time) the card info won't scroll unless you're touching the very bottom edge of the card. Other times, anywhere inside the card-reveal lets you scroll.

**Comment by swglad** [comment]
Did a hard reset and all issues are still present. None of the bugs listed present on ```master```

**Comment by swglad** [comment]
Add link to Profile

**Pull request merged**
